---
title: "Report"
author: "Justin Powley"
format: html
editor: visual
---

```{r, init, message = F, warning = F, error = F}
library(tidyquant)
library(tidyverse)
library(RTL)
library(tsibble)
library(feasts)
library(slider)
library(httr)

EIA_API <- "UKCNbCB0m8aixfPBshQU3Jdlz2uZsEbG2HebvhHX"
```

```{r, data_import}
# Yahoo Finance
tickers <- c("RB=F", "HO=F", "CL=F", "NG=F")
start_date <- '2021-01-01'
price_data_in <- tq_get(tickers, get = "stock.prices", from = start_date) %>% 
  dplyr::mutate(symbol = case_when(symbol == tickers[1] ~ "RBOB",
                                   symbol == tickers[2] ~ "Heating_Oil",
                                   symbol == tickers[3] ~ "WTI",
                                   symbol == tickers[4] ~ "Natural_Gas"))

eia_tickers <- tribble(~ticker, ~name, "PET.WTTSTUS1.W", "US_Crude_Inventory",
                       "PET.MCRFPUS1.M", "US_Crude_Prod",
                       "NG.NW2_EPG0_SWO_R48_BCF.W", "Lower48NGStorage",
                       "PET.WCRNTUS2.W", "US_Crude_NI",
                       "PET.WRPNTUS2.W", "US_Petrol_Products_NI",
                       "PET.WGFRPUS2.W", "US_Gasoline_Production",
                       "PET.MGFSTUS1.M", "US_Gasoline_Stocks_Blended",
                       "PET.M_EPOBGRR_SAE_NUS_MBBL.M", "US_RBOB_Stocks_Unblended",
                       "PET.MO5ST_NUS_1.M", "US_Conventional_Stocks_Unblended",
                       "PET.WPULEUS3.W", "Pct_Operable_Utilization"
                       )

EIA_Data <- eia2tidy_all(eia_tickers, EIA_API)
EIA_Data %>% group_by(series) %>% dplyr::mutate(temp = 1, temp = cumsum(temp)) %>% 
  dplyr::filter(temp == 1) %>% 
  dplyr::select(-temp)
```

```{r, preprocessing}
add_ret_metrics <- function(df_in){
  # Accepts a df with columns value, series, date
  # Adds returns and cumulative return metrics for value.
  df_in %>% 
    group_by(series) %>% 
    arrange(series, date) %>% 
    dplyr::mutate(ret_pct = (value-lag(value))/lag(value),
                  ret_log = log(value/lag(value))) %>% 
    tidyr::drop_na() %>% 
    dplyr::mutate(cret_pct = cumprod(ret_pct+1),
                  cret_log = cumsum(ret_log),
                  year_month = yearmonth(date)) %>% 
    return()
}

price_data <- price_data_in %>% 
  dplyr::select(date, series = symbol, value = close, volume) %>% 
  add_ret_metrics()

fundamentals_data <- EIA_Data %>% 
  add_ret_metrics()

# 3:2:1 Crack Spread used here. Setting below can be used to adjust the crack spread to other ratios, such as 5:3:2
spread_ratio <- c(3,2,1)

spread_data <- price_data %>% 
  pivot_wider(names_from = series, id_cols = date, values_from = value) %>% 
  dplyr::mutate(crack_spread = ((spread_ratio[2]*42*RBOB + 
                                spread_ratio[3]*42*Heating_Oil) - 
                                WTI*spread_ratio[1])/
                                spread_ratio[1])

EIA_Data %>% pivot_wider(names_from = series, id_cols = date, values_from = value) %>% 
  dplyr::arrange(desc(date))
```

```{r, eda}
# Rolling Correlation of RBOB and WTI
spread_data %>% 
  dplyr::mutate(static_cor = cor(WTI,RBOB),
                cor20 = slide2_dbl(RBOB, WTI, cor, .before = 20, .complete = TRUE),
                cor50 = slide2_dbl(RBOB, WTI, cor, .before = 50, .complete = TRUE),
                cor200 = slide2_dbl(RBOB, WTI, cor, .before = 200, .complete = TRUE)
                ) %>% 
  tidyr::drop_na() %>% 
  ggplot() +
  geom_line(aes(x=date, y = cor20, color = "20-Day Corr")) +
  geom_line(aes(x=date, y = cor50, color = "50-Day Corr")) +
  geom_line(aes(x=date, y = cor200, color = "200-Day Corr")) +
  geom_line(aes(x = date, y = static_cor, color = "Static Corr, Full Horizon")) +
  labs(title = "Rolling Correlations, WTI and RBOB",
       subtitle = "How coupled are spreads to the underlying price?",
       x = "Date",
       y = "Correlation",
       color = "Legend") +
  scale_color_manual(values = c("20-Day Corr" = "red", "50-Day Corr" = "blue", "200-Day Corr" = "green", "Static Corr, Full Horizon" = "black"))

# Natural Gas and Spread Price
spread_data %>% 
  ggplot() +
  geom_line(aes(x = date, y = crack_spread), color = "red") +
  geom_line(aes(x = date, y = Natural_Gas), color = "black")

# Crude Stocks
fundamentals_data %>% 
  dplyr::filter(series == "US_Crude_Inventory" & date > start_date) %>% 
  ggplot() +
  geom_line(aes(x = date, y = value)) +
  labs(title = "US Crude Stocks", y = "Thousands of Barrels", x = "Date")

# Crude Stocks, PCT Change
fundamentals_data %>% 
  dplyr::filter(series == "US_Crude_Inventory" & date > start_date) %>% 
  ggplot() +
  geom_line(aes(x = date, y = ret_pct)) +
  labs(title = "US Crude Stocks, Changes in Supply", y = "% Change in Supply", x = "Date")

# Plant Utilization versus Crude Inventories
fundamentals_data %>% 
  pivot_wider(names_from = series, id_cols = date, values_from = value) %>% 
  dplyr::select(Pct_Operable_Utilization, US_Crude_Inventory) %>% 
  tidyr::drop_na() %>% 
  cor()
```

## Recommendation



## Rationale

Crack spreads are typically more stable. They are reflective of the profit a refinery takes from processing crude into refined products such as gasoline and diesel. The stability of a spread largely comes from its 


## Fundamental Market Drivers

## Risk

## Appendix

### Development Notes

```{r, Developer Notes}
# A place for the developer to note potential features and future directions to take the model.

# Can today's crack spread be used to predict tomorrows crude price? Perhaps is the crack spread is favorable enough we can expect a bullish run on crude as companies seek to increase production to capitalize on higher margins.

```